# adoption.py

# Ranks 1–20 → "high"
# Ranks 21–90 → "medium"
# Ranks 91–151 → "low"
crypto_adoption = {
    "India": "high",
    "Nigeria": "high",
    "Indonesia": "high",
    "United States of America": "high",
    "Viet Nam": "high",
    "Ukraine": "high",
    "Russia": "high",
    "Philippines": "high",
    "Pakistan": "high",
    "Brazil": "high",
    "Türkiye": "high",
    "United Kingdom": "high",
    "Venezuela (Bolivarian Republic of)": "high",
    "Mexico": "high",
    "Argentina": "high",
    "Thailand": "high",
    "Cambodia": "high",
    "Canada": "high",
    "Korea, South": "high",
    "China": "high",
    "Germany": "medium",
    "France": "medium",
    "Japan": "medium",
    "Poland": "medium",
    "Spain": "medium",
    "Ethiopia": "medium",
    "Morocco": "medium",
    "Kenya": "medium",
    "Hong Kong": "medium",
    "South Africa": "medium",
    "Afghanistan": "medium",
    "Netherlands": "medium",
    "Uzbekistan": "medium",
    "Uganda": "medium",
    "Bangladesh": "medium",
    "Colombia": "medium",
    "Italy": "medium",
    "Belarus": "medium",
    "Australia": "medium",
    "Taiwan": "medium",
    "Saudi Arabia": "medium",
    "Peru": "medium",
    "Algeria": "medium",
    "Egypt": "medium",
    "Yemen": "medium",
    "Ghana": "medium",
    "Malaysia": "medium",
    "Dem. Rep. of Congo": "medium",
    "Serbia": "medium",
    "Portugal": "medium",
    "Chile": "medium",
    "Bulgaria": "medium",
    "Georgia": "medium",
    "Switzerland": "medium",
    "United Arab Emirates": "medium",
    "Kazakhstan": "medium",
    "Zambia": "medium",
    "Moldova (Republic of)": "medium",
    "Hungary": "medium",
    "Greece": "medium",
    "Tanzania, United Republic of": "medium",
    "Somalia": "medium",
    "Senegal": "medium",
    "Romania": "medium",
    "West Bank and Gaza": "medium",
    "Ecuador": "medium",
    "Belgium": "medium",
    "Iraq": "medium",
    "Israel": "medium",
    "Nepal": "medium",
    "Sri Lanka": "medium",
    "Sweden": "medium",
    "Austria": "medium",
    "Singapore": "medium",
    "Kyrgyzstan": "medium",
    "Armenia": "medium",
    "Burma": "medium",
    "Latvia": "medium",
    "Tunisia": "medium",
    "Bosnia and Herzegovina": "medium",
    "Lithuania": "medium",
    "Finland": "medium",
    "Jordan": "medium",
    "Togo": "medium",
    "Lao People's Democratic Republic": "medium",
    "Slovakia (Slovak Republic)": "medium",
    "Paraguay": "medium",
    "Estonia": "medium",
    "Costa Rica": "medium",
    "Croatia": "medium",
    "Azerbaijan": "low",
    "Dominican Republic": "low",
    "Benin": "low",
    "New Zealand": "low",
    "Madagascar": "low",
    "Macedonia": "low",
    "Norway": "low",
    "Libyan Arab Jamahiriya": "low",
    "Bolivia (Plurinational State of)": "low",
    "Ireland": "low",
    "Denmark": "low",
    "Jamaica": "low",
    "Zimbabwe": "low",
    "El Salvador": "low",
    "Cyprus": "low",
    "Côte d’Ivoire": "low",
    "Albania": "low",
    "Burkina Faso": "low",
    "Andorra": "low",
    "Panama": "low",
    "Puerto Rico": "low",
    "Nicaragua": "low",
    "Honduras": "low",
    "Mozambique": "low",
    "Tajikistan": "low",
    "Rwanda": "low",
    "Cameroon": "low",
    "Guatemala": "low",
    "Uruguay": "low",
    "Luxembourg": "low",
    "Kuwait": "low",
    "Mongolia": "low",
    "Liberia": "low",
    "Maldives": "low",
    "Montenegro": "low",
    "The Bahamas": "low",
    "Haiti": "low",
    "Iran (Islamic Republic of)": "low",
    "Qatar": "low",
    "Namibia": "low",
    "Macao": "low",
    "Bahrain": "low",
    "Malta": "low",
    "Malawi": "low",
    "Trinidad and Tobago": "low",
    "Suriname": "low",
    "Angola": "low",
    "Eq. Guinea": "low",
    "Oman": "low",
    "Iceland": "low",
    "Fiji": "low",
    "Mauritania": "low",
    "Aruba": "low",
    "Mauritius": "low",
    "Belize": "low",
    "Papua New Guinea": "low",
    "Democratic Republic of the Congo": "low",
    "Mali": "low",
    "Botswana": "low"
}
